version: "3"
services:

# MySQL mariadb
  mariadb:
    image: mariadb
    restart: unless-stopped
    env_file: env/mysql.env
    networks:
      - backend

# PostgreSQL
  postgresql:
    image: postgresql
    restart: unless-stopped
    env_file: env/postgresql.env
    networks:
      - backend

# Redis
  redis:
    image: redis
    restart: unless-stopped
    env_file: env/redis.env
    networks:
      - backend

# MongoDB
  mongodb:
    image: mongodb
    restart: unless-stopped
    env_file: env/mongodb.env
    networks:
      - backend


# coTURN
  coturn:
    image: coturn
    restart: unless-stopped
    ports:
## STUN/TURN
      - "3478"
      - "3478/udp"
      - "3479"
      - "3479/udp"
      - "80"
      - "80/udp"
## STUN/TURN SSL
      - "5349"
      - "5349/udp"
      - "5350"
      - "5350/udp"
      - "443"
      - "443/udp"
# Relay Ports
      - "49152-65535"
      - "49152-65535/udp"
    networks:
      - frontend
      - backend
    depends_on:
      - mysql
      - postgresql
      - redis
      - mongodb
    env_file:
      - env/coturn.env
# DB
      - env/mysql.env
      - env/postresql.env
      - env/redis.env
      - env/mongodb.env

networks:
  frontend:
  backend:
